id: P004556
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:32.686683
source_metadata:
  id: bdr:W3CN5574
  title: རྒྱལ་སྲས་ལག་ལེན་རྩ་འགྲེལ།
  author: ''
  volumes:
    99a3216888e74eeab48b504b0ff244f5:
      image_group_id: I3CN5576
      title: ''
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
